version: '3.8'

services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    stdin_open: true
    environment:
      - NODE_ENV=development

volumes:
  mongo-data: